### ISSUE TITLE
Where .tif file do we have?

### ISSUE THREAD

**Issue by tphankr** [nikhilroxtomar/Retina-Blood-Vessel-Segmentation-using-UNET-in-TensorFlow#1]
Please, help us have the link in order to download the .tif original dataset. Because In "new_data" folder is files with .jpg format. 
Thank you very much.

**Comment by nikhilroxtomar** [comment]
For dataset, please have a look at the link https://academictorrents.com/details/062dc18f55b086c76c718ac88f98972789b3c04c

**Comment by tphankr** [comment]
Thank you @nikhilroxtomar.
How do you get 1st_manual and 2nd_manual in the test folder? It's not provided in the dataset. Can you please share the dataset? 
Because I found at your link but in test folder has only "image folder" and "mask foder"; does not have 1st_manual or 2nd_manual folders. How do we find them (1st_manual or 2nd_manual folders).
![image](https://user-images.githubusercontent.com/37217354/118375196-21ae8100-b58e-11eb-888d-2d6d4b8f99a5.png)

![image](https://user-images.githubusercontent.com/37217354/118375183-0ba0c080-b58e-11eb-9832-93cc75c00c6d.png)

Thank you very much.
